# Generated by Django 4.2.2 on 2023-06-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_studentteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTeacher',
        ),
    ]
